export const data = [
  { id: 1, title: 'Apple' },
  { id: 2, title: 'Artichoke' },
  { id: 3, title: 'Asparagus' },
  { id: 4, title: 'Banana' },
  { id: 5, title: 'Beets' },
  { id: 6, title: 'Bell pepper' },
  { id: 7, title: 'Broccoli' },
  { id: 8, title: 'Brussels sprout' },
  { id: 9, title: 'Cabbage' },
  { id: 10, title: 'Carrot' },
  { id: 11, title: 'Cauliflower' },
  { id: 12, title: 'Celery' },
  { id: 13, title: 'Chard' },
  { id: 14, title: 'Chicory' },
  { id: 15, title: 'Corn' },
  { id: 16, title: 'Cucumber' },
  { id: 17, title: 'Daikon' },
  { id: 18, title: 'Date' },
  { id: 19, title: 'Edamame' },
  { id: 20, title: 'Eggplant' },
  { id: 21, title: 'Elderberry' },
  { id: 22, title: 'Fennel' },
  { id: 23, title: 'Fig' },
  { id: 24, title: 'Garlic' },
  { id: 25, title: 'Grape' },
  { id: 26, title: 'Honeydew melon' },
  { id: 27, title: 'Iceberg lettuce' },
  { id: 28, title: 'Jerusalem artichoke' },
  { id: 29, title: 'Kale' },
  { id: 30, title: 'Kiwi' },
  { id: 31, title: 'Leek' },
  { id: 32, title: 'Lemon' },
  { id: 33, title: 'Mango' },
  { id: 34, title: 'Mangosteen' },
  { id: 35, title: 'Melon' },
  { id: 36, title: 'Mushroom' },
  { id: 37, title: 'Nectarine' },
  { id: 38, title: 'Okra' },
  { id: 39, title: 'Olive' },
  { id: 40, title: 'Onion' },
  { id: 41, title: 'Orange' },
  { id: 42, title: 'Parsnip' },
  { id: 43, title: 'Pea' },
  { id: 44, title: 'Pear' },
  { id: 45, title: 'Pineapple' },
  { id: 46, title: 'Potato' },
  { id: 47, title: 'Pumpkin' },
  { id: 48, title: 'Quince' },
  { id: 49, title: 'Radish' },
  { id: 50, title: 'Rhubarb' },
  { id: 51, title: 'Shallot' },
  { id: 52, title: 'Spinach' },
  { id: 53, title: 'Squash' },
  { id: 54, title: 'Strawberry' },
  { id: 55, title: 'Sweet potato' },
  { id: 56, title: 'Tomato' },
  { id: 57, title: 'Turnip' },
  { id: 58, title: 'Ugli fruit' },
  { id: 59, title: 'Victoria plum' },
  { id: 60, title: 'Watercress' },
  { id: 61, title: 'Watermelon' },
  { id: 62, title: 'Yam' },
  { id: 63, title: 'Zucchini' },
  { id: 64, title: 'Test1' },
  { id: 65, title: 'Test2' },
  { id: 66, title: 'Test3' },
  { id: 67, title: 'Test4' },
  { id: 68, title: 'Test5' },
  { id: 69, title: 'Test6' },
  { id: 70, title: 'Test7' },
  { id: 71, title: 'Test8' },
  { id: 72, title: 'Test9' },
  { id: 73, title: 'Test10' },
];
